=== nandojq/noorish/data/recipes/recipe_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Recipe",
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "The name of the recipe"
      },
      "servings": {
        "type": "integer",
        "description": "Number of servings"
      },
      "ingredients": {
        "type": "array",
        "description": "List of ingredients",
        "items": {
          "type": "object",
          "properties": {
            "ingredient": {
              "type": "string",
              "description": "Name of the ingredient. Must be in nutrient database"
            },
            "amount": {
              "type": "number",
              "description": "Amount of the ingredient"
            },
            "amount_unit": {
              "type": "string",
              "description": "Unit of the amount. Must be one of the following: GRAMS, CUP, MILLILITERS, LARGE_UNIT, MEDIUM_UNIT, SMALL_UNIT, TABLESPOON, TEASPOON"
            }
          },
          "required": ["ingredient", "amount", "amount_unit"]
        }
      },
      "prep_instructions": {
        "type": "array",
        "description": "Preparation instructions",
        "items": {
          "type": "string"
        }
      },
      "instructions": {
        "type": "array",
        "description": "Cooking instructions",
        "items": {
          "type": "string"
        }
      },
      "notes": {
        "type": "string",
        "description": "Additional notes for the recipe"
      },
      "prep_time": {
        "type": "integer",
        "description": "Preparation time in minutes"
      },
      "cooking_time": {
        "type": "integer",
        "description": "Cooking time in minutes"
      }
    },
    "required": ["name", "servings", "ingredients", "instructions", "prep_time", "cooking_time"]
  }

=== nandojq/noorish/data/recipes/ramen.json
{
    "name": "Ramen",
    "servings": 2,
    "ingredients": [
      {
        "ingredient": "Dry Ramen Noodles",
        "type": "REQUIRED",
        "amount": 280,
        "amount_unit": "GRAMS"
      },
      {
        "ingredient": "Bok Choy",
        "type": "REQUIRED",
        "amount": 1,
        "amount_unit": "LARGE_UNIT"
      },
      {
        "ingredient": "Nori Seaweed",
        "type": "OPTIONAL",
        "amount": 2,
        "amount_unit": "LARGE_UNIT"
      },
      {
        "ingredient": "Egg",
        "type": "OPTIONAL",
        "amount": 1,
        "amount_unit": "MEDIUM_UNIT"
      },
      {
        "ingredient": "Toasted White Sesame Seeds",
        "type": "REQUIRED",
        "amount": 2,
        "amount_unit": "TABLESPOON"
      },
      {
        "ingredient": "Ginger",
        "type": "REQUIRED",
        "amount": 1.5,
        "amount_unit": "TEASPOON"
      },
      {
        "ingredient": "Sesame Oil",
        "type": "REQUIRED",
        "amount": 1,
        "amount_unit": "TABLESPOON"
      },
      {
        "ingredient": "Garlic Clove",
        "type": "REQUIRED",
        "amount": 2,
        "amount_unit": "MEDIUM_UNIT"
      },
      {
        "ingredient": "Onion",
        "type": "REQUIRED",
        "amount": 1,
        "amount_unit": "LARGE_UNIT"
      },
      {
        "ingredient": "Green Onion",
        "type": "REQUIRED",
        "amount": 2,
        "amount_unit": "MEDIUM_UNIT"
      },
      {
        "ingredient": "Miso Paste",
        "type": "REQUIRED",
        "amount": 1.5,
        "amount_unit": "TABLESPOON"
      },
      {
        "ingredient": "Soy Sauce",
        "type": "REQUIRED",
        "amount": 1.5,
        "amount_unit": "TABLESPOON"
      },
      {
        "ingredient": "Coconut Milk",
        "type": "REQUIRED",
        "amount": 470,
        "amount_unit": "GRAMS"
      },
      {
        "ingredient": "Salt",
        "type": "REQUIRED",
        "amount": 1.5,
        "amount_unit": "TEASPOON"
      },
      {
        "ingredient": "Black Pepper",
        "type": "REQUIRED",
        "amount": 0.5,
        "amount_unit": "TEASPOON"
      },
      {
        "ingredient": "Shiitake Mushroom",
        "type": "REQUIRED",
        "amount": 20,
        "amount_unit": "MEDIUM_UNIT"
      },
      {
        "ingredient": "Olive Oil",
        "type": "REQUIRED",
        "amount": 2,
        "amount_unit": "TABLESPOON"
      },
      {
        "ingredient": "Tomato Paste",
        "type": "REQUIRED",
        "amount": 2,
        "amount_unit": "TEASPOON"
      },
      {
        "ingredient": "Anise Star",
        "type": "REQUIRED",
        "amount": 1,
        "amount_unit": "MEDIUM_UNIT"
      },
      {
        "ingredient": "Water",
        "type": "REQUIRED",
        "amount": 700,
        "amount_unit": "MILLILITERS"
      },
      {
        "ingredient": "Vegetable Broth Cube",
        "type": "REQUIRED",
        "amount": 1,
        "amount_unit": "MEDIUM_UNIT"
      }

    ],
    "prep_instructions": [
        "Cut the onion in big chunks and the green onions, garlic and ginger in small pieces",
        "Cut the Bok Choy and the Shiitake Mushrooms in long cuts",
        "Prepare an Anise Star in an infusion object",
        "Put the water to boil and insert the Vegetable Broth Cube"
    ],
    "instructions": [
      "In a big pot, heat up the olive oil and cook the onion, green onions, garlic and ginger for 2 min until golden",
      "Add the tomato paste and cook for another 2 min, while stirring",
      "Add the vegetable broth and the coconut milk and bring to boiling point",
      "When boling point is achieved, bring down the fire to medium power and add the bok choy, shiitake mushrooms and the anise star",
      "Add the miso paste, soy sauce, sesame oil, sesame seeds, salt and pepper",
      "Stir and let simmer for 25-45 min, check taste 2 or 3 times to adjust salt",
      "Meanwhile, cook the dry ramen noodles in another pot with boiling water and rinse with fresh water when done",
      "When the broth and the noodles are ready, serve together in a bowl with any extra topings"
    ],
    "notes": "Feel free to customize toppings according to your preference, such as adding nori seaweed, bamboo shoots, or chili oil for extra flavor.",
    "prep_time": 10,
    "cooking_time": 45
  }

=== nandojq/noorish/data/recipes/dahl.json
{
    "name": "Dahl",
    "servings": 4,
    "ingredients": [
      {
        "ingredient": "Red Lentils",
        "amount": 190,
        "amount_unit": "GRAMS"
      },
      {
        "ingredient": "Olive Oil",
        "amount": 2,
        "amount_unit": "TABLESPOON"
      },
      {
        "ingredient": "Onion",
        "amount": 1,
        "amount_unit": "UNIT"
      },
      {
        "ingredient": "Garlic",
        "amount": 2,
        "amount_unit": "UNIT"
      },
      {
        "ingredient": "Green Chilli Pepper",
        "amount": 1,
        "amount_unit": "UNIT"
      },
      {
        "ingredient": "Ginger",
        "amount": 1.5,
        "amount_unit": "TEASPOON"
      },
      {
        "ingredient": "Curry Powder",
        "amount": 2,
        "amount_unit": "TEASPOON"
      },
      {
        "ingredient": "Turmeric",
        "amount": 0.5,
        "amount_unit": "TEASPOON"
      },
      {
        "ingredient": "Cumin",
        "amount": 0.5,
        "amount_unit": "TEASPOON"
      },
      {
        "ingredient": "Coriander",
        "amount": 1.5,
        "amount_unit": "TEASPOON"
      },
      {
        "ingredient": "Tomato Paste",
        "amount": 2,
        "amount_unit": "TEASPOON"
      },
      {
        "ingredient": "Water",
        "amount": 350,
        "amount_unit": "MILLILITERS"
      },
      {
        "ingredient": "Coconut Milk",
        "amount": 400,
        "amount_unit": "MILLILITERS"
      },
      {
        "ingredient": "Salt",
        "amount": 2,
        "amount_unit": "TEASPOON"
      }

    ],
    "prep_instructions": [
        "Cut the onion, ginger, pepper and garlic finely",
        "Take off the cilantro leaves, wash them in water",
        "Prepare the spice mix",
        "Add hot water to the red lentils and smash to form a paste"
    ],

    "instructions": [
        "Heat some olive oil in a pan",
        "When the olive is hot, add the onions, ginger, ppeper and garlic",
        "Cook everything until slightly brown",
        "Add tomato paste and the spice mix and cook for 2 min",
        "Add the red lentil paste to the pan",
        "Add the coconut milk",
        "Add salt and black pepper", 
        "Keep cooking until the water reduces, stirring",
        "When ready, turn off the heat and add chopped cilantro to serve"
    ],
    "notes": "Serve with some tahini for nutty flavor",
    "prep_time": 10,
    "cooking_time": 45
  }
